package com.chinasofti.ssmdemo.ssm.dal.dao;

import com.chinasofti.ssmdemo.ssm.dal.entity.BalanceRecord;
import com.chinasofti.ssmdemo.ssm.dal.entity.BalanceRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BalanceRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_record
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    int countByExample(BalanceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_record
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    int deleteByExample(BalanceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_record
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    int deleteByPrimaryKey(Integer balanceRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_record
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    int insert(BalanceRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_record
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    int insertSelective(BalanceRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_record
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    List<BalanceRecord> selectByExample(BalanceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_record
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    BalanceRecord selectByPrimaryKey(Integer balanceRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_record
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") BalanceRecord record, @Param("example") BalanceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_record
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    int updateByExample(@Param("record") BalanceRecord record, @Param("example") BalanceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_record
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    int updateByPrimaryKeySelective(BalanceRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance_record
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    int updateByPrimaryKey(BalanceRecord record);
}