package com.chinasofti.ssmdemo.ssm.dal.dao;

import com.chinasofti.ssmdemo.ssm.dal.entity.BookComment;
import com.chinasofti.ssmdemo.ssm.dal.entity.BookCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    int countByExample(BookCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    int deleteByExample(BookCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    int deleteByPrimaryKey(Integer bookCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    int insert(BookComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    int insertSelective(BookComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    List<BookComment> selectByExample(BookCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    BookComment selectByPrimaryKey(Integer bookCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") BookComment record, @Param("example") BookCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    int updateByExample(@Param("record") BookComment record, @Param("example") BookCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    int updateByPrimaryKeySelective(BookComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    int updateByPrimaryKey(BookComment record);
}