package com.chinasofti.ssmdemo.ssm.dal.dao;

import com.chinasofti.ssmdemo.ssm.dal.entity.OrderListInfo;
import com.chinasofti.ssmdemo.ssm.dal.entity.OrderListInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderListInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    int countByExample(OrderListInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    int deleteByExample(OrderListInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    int deleteByPrimaryKey(Integer orderListId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    int insert(OrderListInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    int insertSelective(OrderListInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    List<OrderListInfo> selectByExample(OrderListInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    OrderListInfo selectByPrimaryKey(Integer orderListId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") OrderListInfo record, @Param("example") OrderListInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    int updateByExample(@Param("record") OrderListInfo record, @Param("example") OrderListInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    int updateByPrimaryKeySelective(OrderListInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_list
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    int updateByPrimaryKey(OrderListInfo record);
}