package com.chinasofti.ssmdemo.ssm.dal.entity;

public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.id
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    private Integer addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.user_id
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.consignee_name
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    private String consigneeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.mobile
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.zip_no
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    private String zipNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.id
     *
     * @return the value of address.id
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.id
     *
     * @param addressId the value for address.id
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.user_id
     *
     * @return the value of address.user_id
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.user_id
     *
     * @param userId the value for address.user_id
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.consignee_name
     *
     * @return the value of address.consignee_name
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public String getConsigneeName() {
        return consigneeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.consignee_name
     *
     * @param consigneeName the value for address.consignee_name
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public void setConsigneeName(String consigneeName) {
        this.consigneeName = consigneeName == null ? null : consigneeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.mobile
     *
     * @return the value of address.mobile
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.mobile
     *
     * @param mobile the value for address.mobile
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.zip_no
     *
     * @return the value of address.zip_no
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public String getZipNo() {
        return zipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.zip_no
     *
     * @param zipNo the value for address.zip_no
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public void setZipNo(String zipNo) {
        this.zipNo = zipNo == null ? null : zipNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address
     *
     * @return the value of address.address
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address
     *
     * @param address the value for address.address
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

	@Override
	public String toString() {
		return "Address [addressId=" + addressId + ", userId=" + userId + ", consigneeName=" + consigneeName
				+ ", mobile=" + mobile + ", zipNo=" + zipNo + ", address=" + address + "]";
	}
}