package com.chinasofti.ssmdemo.ssm.dal.entity;

import java.math.BigDecimal;
import java.util.Date;

public class BalanceRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_record.id
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    private Integer balanceRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_record.user_id
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_record.operation
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    private Integer operation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_record.amount
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_record.operate_time
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    private Date operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance_record.order_id
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    private String orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_record.id
     *
     * @return the value of balance_record.id
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    public Integer getBalanceRecordId() {
        return balanceRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_record.id
     *
     * @param balanceRecordId the value for balance_record.id
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    public void setBalanceRecordId(Integer balanceRecordId) {
        this.balanceRecordId = balanceRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_record.user_id
     *
     * @return the value of balance_record.user_id
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_record.user_id
     *
     * @param userId the value for balance_record.user_id
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_record.operation
     *
     * @return the value of balance_record.operation
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    public Integer getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_record.operation
     *
     * @param operation the value for balance_record.operation
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    public void setOperation(Integer operation) {
        this.operation = operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_record.amount
     *
     * @return the value of balance_record.amount
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_record.amount
     *
     * @param amount the value for balance_record.amount
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_record.operate_time
     *
     * @return the value of balance_record.operate_time
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_record.operate_time
     *
     * @param operateTime the value for balance_record.operate_time
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance_record.order_id
     *
     * @return the value of balance_record.order_id
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance_record.order_id
     *
     * @param orderId the value for balance_record.order_id
     *
     * @mbggenerated Mon Sep 18 14:26:04 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }
}