package com.chinasofti.ssmdemo.ssm.dal.entity;

public class Bankcard {
    @Override
	public String toString() {
		return "Bankcard [id=" + id + ", userId=" + userId + ", bankCardId=" + bankCardId + ", bankCardName="
				+ bankCardName + "]";
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankcard.id
     *
     * @mbggenerated Thu Sep 14 11:29:02 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankcard.user_id
     *
     * @mbggenerated Thu Sep 14 11:29:02 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankcard.bank_card_id
     *
     * @mbggenerated Thu Sep 14 11:29:02 CST 2017
     */
    private String bankCardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bankcard.bank_card_name
     *
     * @mbggenerated Thu Sep 14 11:29:02 CST 2017
     */
    private String bankCardName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankcard.id
     *
     * @return the value of bankcard.id
     *
     * @mbggenerated Thu Sep 14 11:29:02 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankcard.id
     *
     * @param id the value for bankcard.id
     *
     * @mbggenerated Thu Sep 14 11:29:02 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankcard.user_id
     *
     * @return the value of bankcard.user_id
     *
     * @mbggenerated Thu Sep 14 11:29:02 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankcard.user_id
     *
     * @param userId the value for bankcard.user_id
     *
     * @mbggenerated Thu Sep 14 11:29:02 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankcard.bank_card_id
     *
     * @return the value of bankcard.bank_card_id
     *
     * @mbggenerated Thu Sep 14 11:29:02 CST 2017
     */
    public String getBankCardId() {
        return bankCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankcard.bank_card_id
     *
     * @param bankCardId the value for bankcard.bank_card_id
     *
     * @mbggenerated Thu Sep 14 11:29:02 CST 2017
     */
    public void setBankCardId(String bankCardId) {
        this.bankCardId = bankCardId == null ? null : bankCardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bankcard.bank_card_name
     *
     * @return the value of bankcard.bank_card_name
     *
     * @mbggenerated Thu Sep 14 11:29:02 CST 2017
     */
    public String getBankCardName() {
        return bankCardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bankcard.bank_card_name
     *
     * @param bankCardName the value for bankcard.bank_card_name
     *
     * @mbggenerated Thu Sep 14 11:29:02 CST 2017
     */
    public void setBankCardName(String bankCardName) {
        this.bankCardName = bankCardName == null ? null : bankCardName.trim();
    }
}