package com.chinasofti.ssmdemo.ssm.dal.entity;

import java.util.ArrayList;
import java.util.List;

public class BookCommentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public BookCommentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBookCommentIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andBookCommentIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andBookCommentIdEqualTo(Integer value) {
            addCriterion("id =", value, "bookCommentId");
            return (Criteria) this;
        }

        public Criteria andBookCommentIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "bookCommentId");
            return (Criteria) this;
        }

        public Criteria andBookCommentIdGreaterThan(Integer value) {
            addCriterion("id >", value, "bookCommentId");
            return (Criteria) this;
        }

        public Criteria andBookCommentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "bookCommentId");
            return (Criteria) this;
        }

        public Criteria andBookCommentIdLessThan(Integer value) {
            addCriterion("id <", value, "bookCommentId");
            return (Criteria) this;
        }

        public Criteria andBookCommentIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "bookCommentId");
            return (Criteria) this;
        }

        public Criteria andBookCommentIdIn(List<Integer> values) {
            addCriterion("id in", values, "bookCommentId");
            return (Criteria) this;
        }

        public Criteria andBookCommentIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "bookCommentId");
            return (Criteria) this;
        }

        public Criteria andBookCommentIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "bookCommentId");
            return (Criteria) this;
        }

        public Criteria andBookCommentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "bookCommentId");
            return (Criteria) this;
        }

        public Criteria andBookIdIsNull() {
            addCriterion("book_id is null");
            return (Criteria) this;
        }

        public Criteria andBookIdIsNotNull() {
            addCriterion("book_id is not null");
            return (Criteria) this;
        }

        public Criteria andBookIdEqualTo(Integer value) {
            addCriterion("book_id =", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotEqualTo(Integer value) {
            addCriterion("book_id <>", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdGreaterThan(Integer value) {
            addCriterion("book_id >", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("book_id >=", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdLessThan(Integer value) {
            addCriterion("book_id <", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdLessThanOrEqualTo(Integer value) {
            addCriterion("book_id <=", value, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdIn(List<Integer> values) {
            addCriterion("book_id in", values, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotIn(List<Integer> values) {
            addCriterion("book_id not in", values, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdBetween(Integer value1, Integer value2) {
            addCriterion("book_id between", value1, value2, "bookId");
            return (Criteria) this;
        }

        public Criteria andBookIdNotBetween(Integer value1, Integer value2) {
            addCriterion("book_id not between", value1, value2, "bookId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdIsNull() {
            addCriterion("order_item_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdIsNotNull() {
            addCriterion("order_item_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdEqualTo(Integer value) {
            addCriterion("order_item_id =", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdNotEqualTo(Integer value) {
            addCriterion("order_item_id <>", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdGreaterThan(Integer value) {
            addCriterion("order_item_id >", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_item_id >=", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdLessThan(Integer value) {
            addCriterion("order_item_id <", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_item_id <=", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdIn(List<Integer> values) {
            addCriterion("order_item_id in", values, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdNotIn(List<Integer> values) {
            addCriterion("order_item_id not in", values, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdBetween(Integer value1, Integer value2) {
            addCriterion("order_item_id between", value1, value2, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_item_id not between", value1, value2, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andBookCommentIsNull() {
            addCriterion("book_comment is null");
            return (Criteria) this;
        }

        public Criteria andBookCommentIsNotNull() {
            addCriterion("book_comment is not null");
            return (Criteria) this;
        }

        public Criteria andBookCommentEqualTo(String value) {
            addCriterion("book_comment =", value, "bookComment");
            return (Criteria) this;
        }

        public Criteria andBookCommentNotEqualTo(String value) {
            addCriterion("book_comment <>", value, "bookComment");
            return (Criteria) this;
        }

        public Criteria andBookCommentGreaterThan(String value) {
            addCriterion("book_comment >", value, "bookComment");
            return (Criteria) this;
        }

        public Criteria andBookCommentGreaterThanOrEqualTo(String value) {
            addCriterion("book_comment >=", value, "bookComment");
            return (Criteria) this;
        }

        public Criteria andBookCommentLessThan(String value) {
            addCriterion("book_comment <", value, "bookComment");
            return (Criteria) this;
        }

        public Criteria andBookCommentLessThanOrEqualTo(String value) {
            addCriterion("book_comment <=", value, "bookComment");
            return (Criteria) this;
        }

        public Criteria andBookCommentLike(String value) {
            addCriterion("book_comment like", value, "bookComment");
            return (Criteria) this;
        }

        public Criteria andBookCommentNotLike(String value) {
            addCriterion("book_comment not like", value, "bookComment");
            return (Criteria) this;
        }

        public Criteria andBookCommentIn(List<String> values) {
            addCriterion("book_comment in", values, "bookComment");
            return (Criteria) this;
        }

        public Criteria andBookCommentNotIn(List<String> values) {
            addCriterion("book_comment not in", values, "bookComment");
            return (Criteria) this;
        }

        public Criteria andBookCommentBetween(String value1, String value2) {
            addCriterion("book_comment between", value1, value2, "bookComment");
            return (Criteria) this;
        }

        public Criteria andBookCommentNotBetween(String value1, String value2) {
            addCriterion("book_comment not between", value1, value2, "bookComment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_comment
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 13 11:25:51 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}