package com.chinasofti.ssmdemo.ssm.dal.entity;

public class BookComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_comment.id
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    private Integer bookCommentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_comment.book_id
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_comment.order_item_id
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    private Integer orderItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_comment.book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    private String bookComment;

    @Override
	public String toString() {
		return "BookComment [bookCommentId=" + bookCommentId + ", bookId=" + bookId + ", orderItemId=" + orderItemId
				+ ", bookComment=" + bookComment + "]";
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_comment.id
     *
     * @return the value of book_comment.id
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public Integer getBookCommentId() {
        return bookCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_comment.id
     *
     * @param bookCommentId the value for book_comment.id
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public void setBookCommentId(Integer bookCommentId) {
        this.bookCommentId = bookCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_comment.book_id
     *
     * @return the value of book_comment.book_id
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_comment.book_id
     *
     * @param bookId the value for book_comment.book_id
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_comment.order_item_id
     *
     * @return the value of book_comment.order_item_id
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public Integer getOrderItemId() {
        return orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_comment.order_item_id
     *
     * @param orderItemId the value for book_comment.order_item_id
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public void setOrderItemId(Integer orderItemId) {
        this.orderItemId = orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_comment.book_comment
     *
     * @return the value of book_comment.book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public String getBookComment() {
        return bookComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_comment.book_comment
     *
     * @param bookComment the value for book_comment.book_comment
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public void setBookComment(String bookComment) {
        this.bookComment = bookComment == null ? null : bookComment.trim();
    }
}