package com.chinasofti.ssmdemo.ssm.dal.entity;

import java.math.BigDecimal;

public class Book {
    @Override
	public String toString() {
		return "Book [bookId=" + bookId + ", name=" + name + ", author=" + author + ", price=" + price + ", primeCost="
				+ primeCost + ", count=" + count + ", bookStatus=" + bookStatus + ", categoryId=" + categoryId
				+ ", bookDescribe=" + bookDescribe + ", imgUrl=" + imgUrl + "]";
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.id
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.name
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.author
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.price
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.prime_cost
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    private BigDecimal primeCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.count
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_status
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    private Integer bookStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.category_id
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_describe
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    private String bookDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.img_url
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    private String imgUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.id
     *
     * @return the value of book.id
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.id
     *
     * @param bookId the value for book.id
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.name
     *
     * @return the value of book.name
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.name
     *
     * @param name the value for book.name
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.author
     *
     * @return the value of book.author
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.author
     *
     * @param author the value for book.author
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.price
     *
     * @return the value of book.price
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.price
     *
     * @param price the value for book.price
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.prime_cost
     *
     * @return the value of book.prime_cost
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public BigDecimal getPrimeCost() {
        return primeCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.prime_cost
     *
     * @param primeCost the value for book.prime_cost
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public void setPrimeCost(BigDecimal primeCost) {
        this.primeCost = primeCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.count
     *
     * @return the value of book.count
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.count
     *
     * @param count the value for book.count
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_status
     *
     * @return the value of book.book_status
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public Integer getBookStatus() {
        return bookStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_status
     *
     * @param bookStatus the value for book.book_status
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public void setBookStatus(Integer bookStatus) {
        this.bookStatus = bookStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.category_id
     *
     * @return the value of book.category_id
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.category_id
     *
     * @param categoryId the value for book.category_id
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_describe
     *
     * @return the value of book.book_describe
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public String getBookDescribe() {
        return bookDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_describe
     *
     * @param bookDescribe the value for book.book_describe
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public void setBookDescribe(String bookDescribe) {
        this.bookDescribe = bookDescribe == null ? null : bookDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.img_url
     *
     * @return the value of book.img_url
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.img_url
     *
     * @param imgUrl the value for book.img_url
     *
     * @mbggenerated Wed Sep 13 11:25:51 CST 2017
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }
}