package com.chinasofti.ssmdemo.ssm.dal.entity;

import java.math.BigDecimal;

public class Cart {
	
	
	
    @Override
	public String toString() {
		return "Cart [cartId=" + cartId + ", userId=" + userId + ", bookId=" + bookId + ", bookName=" + bookName
				+ ", count=" + count + ", totalAmount=" + totalAmount + "]";
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.id
     *
     * @mbggenerated Fri Sep 15 15:04:32 CST 2017
     */
    private Integer cartId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.user_id
     *
     * @mbggenerated Fri Sep 15 15:04:32 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.book_id
     *
     * @mbggenerated Fri Sep 15 15:04:32 CST 2017
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.book_name
     *
     * @mbggenerated Fri Sep 15 15:04:32 CST 2017
     */
    private String bookName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.count
     *
     * @mbggenerated Fri Sep 15 15:04:32 CST 2017
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.total_amount
     *
     * @mbggenerated Fri Sep 15 15:04:32 CST 2017
     */
    private BigDecimal totalAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.id
     *
     * @return the value of cart.id
     *
     * @mbggenerated Fri Sep 15 15:04:32 CST 2017
     */
    public Integer getCartId() {
        return cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.id
     *
     * @param cartId the value for cart.id
     *
     * @mbggenerated Fri Sep 15 15:04:32 CST 2017
     */
    public void setCartId(Integer cartId) {
        this.cartId = cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.user_id
     *
     * @return the value of cart.user_id
     *
     * @mbggenerated Fri Sep 15 15:04:32 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.user_id
     *
     * @param userId the value for cart.user_id
     *
     * @mbggenerated Fri Sep 15 15:04:32 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.book_id
     *
     * @return the value of cart.book_id
     *
     * @mbggenerated Fri Sep 15 15:04:32 CST 2017
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.book_id
     *
     * @param bookId the value for cart.book_id
     *
     * @mbggenerated Fri Sep 15 15:04:32 CST 2017
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.book_name
     *
     * @return the value of cart.book_name
     *
     * @mbggenerated Fri Sep 15 15:04:32 CST 2017
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.book_name
     *
     * @param bookName the value for cart.book_name
     *
     * @mbggenerated Fri Sep 15 15:04:32 CST 2017
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.count
     *
     * @return the value of cart.count
     *
     * @mbggenerated Fri Sep 15 15:04:32 CST 2017
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.count
     *
     * @param count the value for cart.count
     *
     * @mbggenerated Fri Sep 15 15:04:32 CST 2017
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.total_amount
     *
     * @return the value of cart.total_amount
     *
     * @mbggenerated Fri Sep 15 15:04:32 CST 2017
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.total_amount
     *
     * @param totalAmount the value for cart.total_amount
     *
     * @mbggenerated Fri Sep 15 15:04:32 CST 2017
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }
}