package com.chinasofti.ssmdemo.ssm.dal.entity;

import java.math.BigDecimal;
import java.util.Date;

public class OrderListInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.id
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    private Integer orderListId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.user_id
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.user_name
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.order_id
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.total_amount
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    private BigDecimal totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.address_id
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    private Integer addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.address_name
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    private String addressName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.return_amount
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    private BigDecimal returnAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.create_time
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.end_time
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_list.status
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.id
     *
     * @return the value of order_list.id
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    public Integer getOrderListId() {
        return orderListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.id
     *
     * @param orderListId the value for order_list.id
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    public void setOrderListId(Integer orderListId) {
        this.orderListId = orderListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.user_id
     *
     * @return the value of order_list.user_id
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.user_id
     *
     * @param userId the value for order_list.user_id
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.user_name
     *
     * @return the value of order_list.user_name
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.user_name
     *
     * @param userName the value for order_list.user_name
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.order_id
     *
     * @return the value of order_list.order_id
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.order_id
     *
     * @param orderId the value for order_list.order_id
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.total_amount
     *
     * @return the value of order_list.total_amount
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.total_amount
     *
     * @param totalAmount the value for order_list.total_amount
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.address_id
     *
     * @return the value of order_list.address_id
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.address_id
     *
     * @param addressId the value for order_list.address_id
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.address_name
     *
     * @return the value of order_list.address_name
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    public String getAddressName() {
        return addressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.address_name
     *
     * @param addressName the value for order_list.address_name
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    public void setAddressName(String addressName) {
        this.addressName = addressName == null ? null : addressName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.return_amount
     *
     * @return the value of order_list.return_amount
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    public BigDecimal getReturnAmount() {
        return returnAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.return_amount
     *
     * @param returnAmount the value for order_list.return_amount
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    public void setReturnAmount(BigDecimal returnAmount) {
        this.returnAmount = returnAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.create_time
     *
     * @return the value of order_list.create_time
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.create_time
     *
     * @param createTime the value for order_list.create_time
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.end_time
     *
     * @return the value of order_list.end_time
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.end_time
     *
     * @param endTime the value for order_list.end_time
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_list.status
     *
     * @return the value of order_list.status
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_list.status
     *
     * @param status the value for order_list.status
     *
     * @mbggenerated Wed Sep 20 19:48:18 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}